apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-test-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  source:
    repoURL: https://github.com/zilinjak/k8s-playground-apps.git
    path: helm/envoy-test
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
