apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep-app
  template:
    metadata:
      labels:
        app: sleep-app
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "6000"]
