apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  source:
    helm:
      values: |
        certgen.job.ttlSecondsAfterFinished: 1
    repoURL: 'registry-1.docker.io/envoyproxy'
    chart: gateway-helm
    path: gateway-helm
    targetRevision: v1.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
