# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: envoy
# spec:
#   project: default
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: envoy-gateway
#   source:
#     helm:
#       values: |
        
#     repoURL: 'registry-1.docker.io/envoyproxy'
#     chart: gateway-helm
#     path: gateway-helm
#     targetRevision: v0.4.0
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  source:
    repoURL: https://github.com/zilinjak/k8s-playground-apps.git
    path: helm/gateway-helm
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true