apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  source:
    helm:
      values: |
        alertmanager.enabled: false
        kube-state-metrics.enabled: false
        prometheus-node-exporter.enabled: false
        prometheus-pushgateway.enabled: false
        hostRootFsMount:
          enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.20.1 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
