apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  source:
    helm:
      values: |
        alertmanager.enabled: false
        kube-state-metrics.enabled: false
        prometheus-node-exporter.enabled: false
        prometheus-pushgateway.enabled: false
    repoURL: https://github.com/prometheus-community/helm-charts/
    chart: prometheus-community/prometheus
    targetRevision: f29a2580f698ab6cac895785fe72886c8a42fec7
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
