apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    helm:
      values: |
        alertmanager.enabled: false
        kube-state-metrics.enabled: false
        prometheus-node-exporter.enabled: false
        prometheus-pushgateway.enabled: false
    repoURL: https://charts.helm.sh/stable
    chart: prometheus-community/prometheus
    targetRevision: main