apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  source:
    helm:
      values: |
        alertmanager:
          enabled: true
          service:
            type: LoadBalancer
        kube-state-metrics:
          enabled: true
        prometheus-pushgateway:
          enabled: true

        prometheus-node-exporter:
          enabled: true
          hostRootFsMount:
            enabled: false
        server:
          service:
            type: LoadBalancer
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.20.1 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
