apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: infra
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30901
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: main
